name: 问题反馈
description: "反馈你遇到的问题"
title: "此处填写简洁明了的标题"
labels:
  - "bug"
body:
  - type: checkboxes
    attributes:
      label: 先决条件
      description: 在提交之前，请勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭
      options:
        - label: 我已填写一个简洁明了的标题，以便他人快速检索
        - label: 我已下载最新版本测试，问题依然存在
        - label: 我已查阅 [使用说明](https://github.com/freeok/so-novel/blob/main/input/readme.txt) 以及 [常见问题](https://github.com/freeok/so-novel?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
        - label: 我已确保 [已有的问题](./?q=is%3Aissue) 中无类似 issue，否则请在已有的 issue 内进行讨论
        - label: 我已关闭所有杀毒软件/代理软件后测试，问题依然存在

  - type: dropdown
    attributes:
      label: 操作系统名称
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    attributes:
      label: 操作系统版本
    validations:
      required: true

  - type: input
    attributes:
      label: so-novel 版本
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 详细清晰地描述你遇到的问题，并提供截图
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现步骤
      description: 请提供复现问题的步骤
    validations:
      required: true