name: 功能请求
description: 我希望新增/改进某个功能
title: '[功能请求] 此处填写简洁明了的标题'
labels:
  - "enhancement"

body:
  - type: checkboxes
    attributes:
      label: 先决条件
      description: 在提交之前，请勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭
      options:
        - label: 我确保软件不存在类似的功能，即便是最新版本
        - label: 我确保 [已有的问题](./?q=is%3Aissue) 中没有人提交过类似 issue，否则请在已有的 issue 下进行讨论
        - label: 我确保给 issue 填写一个简洁明了的标题，以便他人快速检索

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请详细清晰地描述你的功能请求
    validations:
      required: true
  - type: textarea
    attributes:
      label: 使用场景
      description: 请描述你的功能请求的使用场景
    validations:
      required: true