name: 问题反馈
description: 反馈你遇到的问题
title: '[问题反馈] 此处填写简洁明了的标题'
body:
  - type: checkboxes
    attributes:
      label: 先决条件
      description: 在提交之前，请勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭
      options:
        - label: 我已下载最新版本测试，问题依然存在
        - label: 我已认真查阅 [使用说明](https://github.com/freeok/so-novel/blob/main/bundle/readme.txt) 以及 [常见问题](https://github.com/freeok/so-novel?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
        - label: 我已确保 [已有问题](./issues?q=is%3Aissue) 中无类似 issue，否则请在已有的 issue 内进行讨论
        - label: 我已开启&关闭所有代理软件后测试，问题依然存在
        - label: 我已填写一个简洁明了的标题，以便他人快速检索

  - type: dropdown
    attributes:
      label: 操作系统名称
      options:
        - Windows
        - macOS
        - Linux
        - Others
    validations:
      required: true

  - type: textarea
    attributes:
      label: 操作系统版本（Windows：运行 winver，Linux：运行 lsb_release -a，macOS：运行 sw_vers 查看）
      placeholder: 结果粘贴到此处
    validations:
      required: true

  - type: input
    attributes:
      label: so-novel 版本
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: 配置信息
      placeholder: 选择功能d.配置信息，结果粘贴到此处
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 简要地描述你遇到的问题，并提供完整的输入&输出信息，尽量用截图
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现步骤
      description: 请提供复现该问题的完整步骤
    validations:
      required: true