name: 推荐书源
description: 我希望增加某个书源
title: '【推荐书源】此处填写书源网址'
labels:
  - "new source"
body:
  - type: markdown
    attributes:
      value: |
        ## 先决条件

  - type: markdown
    attributes:
      value: |
        - 无付费
        - 支持搜索
        - 无需输入验证码、无需点击“确认您是真人”
        - 国内网络可直连访问（优质书源可忽略）

  - type: checkboxes
    attributes:
      label: 确定推荐的书源均满足以上条件？
      options:
        - label: "Yes"
          required: true

  - type: markdown
    attributes:
      value: |
        ## 填写内容

  - type: input
    attributes:
      label: 书源网址
      placeholder: https://example.com/
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 书源类型
      options:
        - 网络小说
        - 轻小说
        - 综合
        - 其它（需在推荐理由填写具体类型）
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 勾选满足的条件，不确定的不勾选
      options:
        - label: 起点月票榜的书能搜到：https://www.qidian.com/rank/yuepiao/
        - label: 起点收藏榜的书能搜到：https://www.qidian.com/rank/collect/
        - label: 能搜到知名小说
        - label: 正文内容纯净（没有与文章无关的内容）
        - label: 正文错别字少
        - label: 正文排版正常

  - type: textarea
    attributes:
      label: 推荐理由
    validations:
      required: true